---
name: CI

on: # yamllint disable-line rule:truthy
  pull_request:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write

jobs:
  verify_module:
    name: Verify module
    strategy:
      matrix:
        terraform: [ 1.6.1 ]
    runs-on: ubuntu-latest
    container:
      image: hashicorp/terraform:${{ matrix.terraform }}
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - run: terraform init -get -backend=false -input=false
      - run: terraform fmt -recursive -check=true -write=false
      - run: terraform validate
